export const MarketplaceAbi = [
  {
    type: "constructor",
    inputs: [
      {
        name: "_escrowContract",
        type: "address",
        internalType: "address payable",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "buyerOrders",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "cancelOrder",
    inputs: [{ name: "_orderId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "confirmOrder",
    inputs: [{ name: "_orderId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createOrder",
    inputs: [
      { name: "_productId", type: "uint256", internalType: "uint256" },
      { name: "_quantity", type: "uint256", internalType: "uint256" },
      {
        name: "_shippingAddress",
        type: "string",
        internalType: "string",
      },
    ],
    outputs: [
      { name: "orderId", type: "uint256", internalType: "uint256" },
      { name: "escrowId", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "createProduct",
    inputs: [
      { name: "_name", type: "string", internalType: "string" },
      { name: "_description", type: "string", internalType: "string" },
      { name: "_price", type: "uint256", internalType: "uint256" },
      { name: "_stock", type: "uint256", internalType: "uint256" },
      { name: "_ipfsHash", type: "string", internalType: "string" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "escrowContract",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract Escrow" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getBuyerOrders",
    inputs: [{ name: "_buyer", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256[]", internalType: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getOrderCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getProductCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getProducts",
    inputs: [
      {
        name: "_productIds",
        type: "uint256[]",
        internalType: "uint256[]",
      },
    ],
    outputs: [
      {
        name: "",
        type: "tuple[]",
        internalType: "struct Marketplace.Product[]",
        components: [
          { name: "id", type: "uint256", internalType: "uint256" },
          { name: "seller", type: "address", internalType: "address" },
          { name: "name", type: "string", internalType: "string" },
          {
            name: "description",
            type: "string",
            internalType: "string",
          },
          { name: "price", type: "uint256", internalType: "uint256" },
          { name: "stock", type: "uint256", internalType: "uint256" },
          { name: "ipfsHash", type: "string", internalType: "string" },
          { name: "isActive", type: "bool", internalType: "bool" },
          {
            name: "createdAt",
            type: "uint256",
            internalType: "uint256",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getSellerOrders",
    inputs: [{ name: "_seller", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256[]", internalType: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getSellerProducts",
    inputs: [{ name: "_seller", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256[]", internalType: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isSeller",
    inputs: [{ name: "_addr", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "orderCounter",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "orders",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "id", type: "uint256", internalType: "uint256" },
      { name: "productId", type: "uint256", internalType: "uint256" },
      { name: "buyer", type: "address", internalType: "address" },
      { name: "seller", type: "address", internalType: "address" },
      { name: "quantity", type: "uint256", internalType: "uint256" },
      { name: "totalAmount", type: "uint256", internalType: "uint256" },
      {
        name: "shippingAddress",
        type: "string",
        internalType: "string",
      },
      {
        name: "status",
        type: "uint8",
        internalType: "enum Marketplace.OrderStatus",
      },
      { name: "createdAt", type: "uint256", internalType: "uint256" },
      { name: "escrowId", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "productCounter",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "products",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "id", type: "uint256", internalType: "uint256" },
      { name: "seller", type: "address", internalType: "address" },
      { name: "name", type: "string", internalType: "string" },
      { name: "description", type: "string", internalType: "string" },
      { name: "price", type: "uint256", internalType: "uint256" },
      { name: "stock", type: "uint256", internalType: "uint256" },
      { name: "ipfsHash", type: "string", internalType: "string" },
      { name: "isActive", type: "bool", internalType: "bool" },
      { name: "createdAt", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "registerSeller",
    inputs: [
      { name: "_storeName", type: "string", internalType: "string" },
      { name: "_description", type: "string", internalType: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "removeProduct",
    inputs: [{ name: "_productId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "sellerOrders",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "sellerProducts",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "sellers",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [
      {
        name: "sellerAddress",
        type: "address",
        internalType: "address",
      },
      { name: "storeName", type: "string", internalType: "string" },
      { name: "description", type: "string", internalType: "string" },
      { name: "isActive", type: "bool", internalType: "bool" },
      { name: "registeredAt", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setEscrowContract",
    inputs: [
      {
        name: "_escrow",
        type: "address",
        internalType: "address payable",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "_newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateProduct",
    inputs: [
      { name: "_productId", type: "uint256", internalType: "uint256" },
      { name: "_price", type: "uint256", internalType: "uint256" },
      { name: "_stock", type: "uint256", internalType: "uint256" },
      { name: "_isActive", type: "bool", internalType: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "OrderCreated",
    inputs: [
      {
        name: "orderId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "productId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "buyer",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "seller",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "totalAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "escrowId",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OrderStatusChanged",
    inputs: [
      {
        name: "orderId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "oldStatus",
        type: "uint8",
        indexed: false,
        internalType: "enum Marketplace.OrderStatus",
      },
      {
        name: "newStatus",
        type: "uint8",
        indexed: false,
        internalType: "enum Marketplace.OrderStatus",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ProductCreated",
    inputs: [
      {
        name: "productId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "seller",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "name",
        type: "string",
        indexed: false,
        internalType: "string",
      },
      {
        name: "price",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ProductRemoved",
    inputs: [
      {
        name: "productId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "seller",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ProductUpdated",
    inputs: [
      {
        name: "productId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "newPrice",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "newStock",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "isActive",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SellerRegistered",
    inputs: [
      {
        name: "seller",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "storeName",
        type: "string",
        indexed: false,
        internalType: "string",
      },
      {
        name: "registeredAt",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "Marketplace__AlreadySeller", inputs: [] },
  { type: "error", name: "Marketplace__EscrowNotSet", inputs: [] },
  { type: "error", name: "Marketplace__InvalidIPFSHash", inputs: [] },
  { type: "error", name: "Marketplace__InvalidPrice", inputs: [] },
  { type: "error", name: "Marketplace__NotProductOwner", inputs: [] },
  { type: "error", name: "Marketplace__NotSeller", inputs: [] },
  { type: "error", name: "Marketplace__OrderNotFound", inputs: [] },
  { type: "error", name: "Marketplace__ProductNotActive", inputs: [] },
  { type: "error", name: "Marketplace__ProductNotFound", inputs: [] },
  { type: "error", name: "Marketplace__Unauthorized", inputs: [] },
];

export const EscrowAbi = [
  { type: "constructor", inputs: [], stateMutability: "nonpayable" },
  { type: "receive", stateMutability: "payable" },
  {
    type: "function",
    name: "DISPUTE_WINDOW",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "buyerEscrows",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "createEscrow",
    inputs: [
      { name: "_buyer", type: "address", internalType: "address" },
      { name: "_seller", type: "address", internalType: "address" },
      { name: "_productId", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "emergencyWithdraw",
    inputs: [
      { name: "_to", type: "address", internalType: "address payable" },
      { name: "_amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "escrowCounter",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "escrows",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "id", type: "uint256", internalType: "uint256" },
      { name: "buyer", type: "address", internalType: "address" },
      { name: "seller", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
      { name: "productId", type: "uint256", internalType: "uint256" },
      {
        name: "status",
        type: "uint8",
        internalType: "enum Escrow.EscrowStatus",
      },
      { name: "createdAt", type: "uint256", internalType: "uint256" },
      {
        name: "disputeRaisedAt",
        type: "uint256",
        internalType: "uint256",
      },
      { name: "resolver", type: "address", internalType: "address" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getBuyerEscrows",
    inputs: [{ name: "_buyer", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256[]", internalType: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getDisputeTimeRemaining",
    inputs: [{ name: "_escrowId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getEscrow",
    inputs: [{ name: "_escrowId", type: "uint256", internalType: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct Escrow.EscrowData",
        components: [
          { name: "id", type: "uint256", internalType: "uint256" },
          { name: "buyer", type: "address", internalType: "address" },
          { name: "seller", type: "address", internalType: "address" },
          { name: "amount", type: "uint256", internalType: "uint256" },
          {
            name: "productId",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "status",
            type: "uint8",
            internalType: "enum Escrow.EscrowStatus",
          },
          {
            name: "createdAt",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "disputeRaisedAt",
            type: "uint256",
            internalType: "uint256",
          },
          { name: "resolver", type: "address", internalType: "address" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getSellerEscrows",
    inputs: [{ name: "_seller", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256[]", internalType: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isDisputeWindowOpen",
    inputs: [{ name: "_escrowId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "marketplace",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "raiseDispute",
    inputs: [{ name: "_escrowId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "refund",
    inputs: [{ name: "_escrowId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "releasePayment",
    inputs: [{ name: "_escrowId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "resolveDispute",
    inputs: [
      { name: "_escrowId", type: "uint256", internalType: "uint256" },
      { name: "_releaseToSeller", type: "bool", internalType: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "sellerEscrows",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setMarketplace",
    inputs: [
      { name: "_marketplace", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "_newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "DisputeRaised",
    inputs: [
      {
        name: "escrowId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "raisedBy",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "raisedAt",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "DisputeResolved",
    inputs: [
      {
        name: "escrowId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "resolution",
        type: "uint8",
        indexed: false,
        internalType: "enum Escrow.EscrowStatus",
      },
      {
        name: "resolver",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "EscrowCreated",
    inputs: [
      {
        name: "escrowId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "buyer",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "seller",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "productId",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "MarketplaceSet",
    inputs: [
      {
        name: "marketplace",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PaymentReleased",
    inputs: [
      {
        name: "escrowId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "seller",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RefundIssued",
    inputs: [
      {
        name: "escrowId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "buyer",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "Escrow__AlreadyRefunded", inputs: [] },
  { type: "error", name: "Escrow__AlreadyReleased", inputs: [] },
  { type: "error", name: "Escrow__DisputeAlreadyRaised", inputs: [] },
  { type: "error", name: "Escrow__DisputeWindowClosed", inputs: [] },
  { type: "error", name: "Escrow__EscrowNotFound", inputs: [] },
  { type: "error", name: "Escrow__InvalidAmount", inputs: [] },
  { type: "error", name: "Escrow__InvalidState", inputs: [] },
  { type: "error", name: "Escrow__NoDispute", inputs: [] },
  { type: "error", name: "Escrow__NotAuthorized", inputs: [] },
  { type: "error", name: "Escrow__TransferFailed", inputs: [] },
  { type: "error", name: "Escrow__ZeroAddress", inputs: [] },
];
